import { getAllSnapshots, computeFacilitySnapshot, daysOfStockRemaining } from "@/lib/data/alertEngine";
import { FACILITIES, STOCK_ITEMS, getStockHistory } from "@/lib/data/store";
import { getForecast as fetchForecast } from "@/lib/forecastingClient";
import { computeAllProposals } from "@/lib/redistribution";
import type { FunctionDeclaration } from "./client";

function findFacility(name: string) {
  const needle = name.trim().toLowerCase();
  return (
    FACILITIES.find((f) => f.name.toLowerCase() === needle) ??
    FACILITIES.find((f) => f.name.toLowerCase().includes(needle)) ??
    FACILITIES.find((f) => needle.includes(f.ward.toLowerCase()))
  );
}

function findItem(name: string) {
  const needle = name.trim().toLowerCase();
  return (
    STOCK_ITEMS.find((i) => i.name.toLowerCase() === needle) ??
    STOCK_ITEMS.find((i) => i.name.toLowerCase().includes(needle)) ??
    STOCK_ITEMS.find((i) => needle.includes(i.category))
  );
}

export const TOOL_DECLARATIONS: FunctionDeclaration[] = [
  {
    name: "list_at_risk_facilities",
    description:
      "List every health facility in Kilifi County currently at stock-out, bed-pressure, or staffing risk, sorted worst-first. Use this to answer 'which facilities are at risk' style questions.",
    parameters: { type: "object", properties: {} },
  },
  {
    name: "get_facility_status",
    description:
      "Get the full current status of one named facility: health score, stock risk, bed occupancy, doctor attendance, patient footfall, and active alerts.",
    parameters: {
      type: "object",
      properties: {
        facilityName: { type: "string", description: "The facility name, or part of it, e.g. 'Ganze' or 'Kilifi'." },
      },
      required: ["facilityName"],
    },
  },
  {
    name: "get_forecast",
    description:
      "Get the AI stock-out forecast for one medicine/item at one facility -- days remaining until stock-out and the projection method used.",
    parameters: {
      type: "object",
      properties: {
        facilityName: { type: "string", description: "The facility name, or part of it." },
        itemName: { type: "string", description: "The medicine or item name, or part of it, e.g. 'Artemether' or 'malaria test'." },
      },
      required: ["facilityName", "itemName"],
    },
  },
  {
    name: "list_redistribution_proposals",
    description:
      "List the currently proposed cross-facility stock transfers (source, destination, item, quantity, urgency) generated by the redistribution optimizer.",
    parameters: { type: "object", properties: {} },
  },
];

export async function executeTool(name: string, args: Record<string, unknown>): Promise<Record<string, unknown>> {
  switch (name) {
    case "list_at_risk_facilities": {
      const snapshots = getAllSnapshots().filter((s) => s.stockRisk !== "ok" || s.alerts.length > 0);
      return {
        facilities: snapshots.map((s) => ({
          name: s.facility.name,
          ward: s.facility.ward,
          healthScore: s.healthScore,
          stockRisk: s.stockRisk,
          topAlert: s.alerts[0]?.message ?? null,
        })),
      };
    }

    case "get_facility_status": {
      const facility = findFacility(String(args.facilityName ?? ""));
      if (!facility) return { error: `No facility found matching "${args.facilityName}"` };
      const snapshot = computeFacilitySnapshot(facility.id);
      return {
        facility: facility.name,
        ward: facility.ward,
        healthScore: snapshot.healthScore,
        stockRisk: snapshot.stockRisk,
        bedOccupancyPct: snapshot.bedOccupancyPct,
        doctorAttendancePct: snapshot.doctorAttendancePct,
        footfallToday: snapshot.footfallToday,
        testKitsMissing: snapshot.testKitsMissing,
        alerts: snapshot.alerts.map((a) => a.message),
      };
    }

    case "get_forecast": {
      const facility = findFacility(String(args.facilityName ?? ""));
      const item = findItem(String(args.itemName ?? ""));
      if (!facility) return { error: `No facility found matching "${args.facilityName}"` };
      if (!item) return { error: `No item found matching "${args.itemName}"` };
      const history = getStockHistory(facility.id, item.id);
      const result = await fetchForecast(history, 14);
      const daysRemainingNow = daysOfStockRemaining(facility.id, item.id);
      return {
        facility: facility.name,
        item: item.name,
        daysRemainingNow: Number.isFinite(daysRemainingNow) ? Math.round(daysRemainingNow * 10) / 10 : null,
        daysToStockout: result.daysToStockout,
        method: result.method,
        confidence: result.confidence,
      };
    }

    case "list_redistribution_proposals": {
      const { proposals } = await computeAllProposals();
      return {
        proposals: proposals.slice(0, 10).map((p) => {
          const item = STOCK_ITEMS.find((i) => i.id === p.itemId);
          return {
            item: item?.name,
            quantity: p.quantity,
            urgency: p.urgency,
            estTransitMinutes: p.estTransitMinutes,
            status: p.status,
          };
        }),
      };
    }

    default:
      return { error: `Unknown tool: ${name}` };
  }
}
